[build]
  command = "echo 'No se requiere build para este sitio estático'"
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  autoLaunch = false
  framework = "#static"

[context.production.environment]
  NODE_VERSION = "16"